version: "3.9"

services:
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: ["pnpm", "start"]

  web-dev:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: development
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "800"
      NEXT_WEBPACK_USEPOLLING: "1"
      NEXT_DISABLE_TURBOPACK: "1"
    volumes:
      - ./front:/app
      - /app/node_modules
    command: >
      sh -c "corepack enable &&
             ([ -d node_modules ] || pnpm install) &&
             pnpm run dev --hostname 0.0.0.0 --port 3000 --webpack"

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: prod
    working_dir: /app
    environment:
      ENVIRONMENT: production
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  api-dev:
    build:
      context: ./back
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    environment:
      ENVIRONMENT: development
    volumes:
      - ./back:/app
    ports:
      - "8001:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
